### ISSUE TITLE
KafkaTrackingToken has no partitions assigned

### ISSUE THREAD

**Issue by ghilainm** [AxonFramework/extension-kafka#2]
I am using Spring Boot and Axon Kafka 4-RC.2

 I have the following configuration 
```
axon:
  eventhandling:
    processors:
      # This name is referenced in the @ProcessingGroup annotation
      kafka-event-processor:
        # Mandatory if you want to not miss any message, otherwise it is a subscribing event processor and you get only notified about newly emitted event
        # The other mode can be used if you don't want to use a database
        mode: "TRACKING"
        source: "b2gMessageSource"
        # Number of threads dedicated to event processing. Keep it to one if the scaling model is the process.
        # If the threadCount * number of processes is smaller than the number of segment some Kafka partitions will not be consumed!
        threadCount: 1
        # Segments define the parallelism in Axon. Kafka partitions are mapped to segments.
        # Should be aligned with the number of partitions in the topic to ensure maximum parallelism.
        initialSegmentCount: 1
  kafka:
    # Must be transit to consume from transit topic
    default-topic: "transit"
    consumer:
      # Choose a group id for your consumer group, this property triggers the configuration of the KafkaMessageSource referenced in the event process defined above
      group-id: "axon-gateway-b2g-consumer"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
```

I have also disable Axon auto configuration for kafka because it seems to be buggy.

I have added the following configuration class:

```
package b2ggateway.out;

import java.util.concurrent.TimeUnit;

import org.axonframework.extensions.kafka.KafkaProperties;
import org.axonframework.extensions.kafka.eventhandling.DefaultKafkaMessageConverter;
import org.axonframework.extensions.kafka.eventhandling.KafkaMessageConverter;
import org.axonframework.extensions.kafka.eventhandling.consumer.*;
import org.axonframework.serialization.Serializer;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Customization of the {@link org.axonframework.extensions.kafka.autoconfig.KafkaAutoConfiguration} which seems to be buggy.
 * The name of the method have been changed to avoid the bean overriding issue leading to ConsumerFactory not being created.
 */
@SuppressWarnings("unchecked")
@Configuration
@EnableConfigurationProperties({KafkaProperties.class})
public class AxonConfig {
    private final KafkaProperties properties;

    public AxonConfig(KafkaProperties properties) {
        this.properties = properties;
    }

    @Bean
    public ConsumerFactory<String, byte[]> b2gConsumerFactory() {
        return new DefaultConsumerFactory(this.properties.buildConsumerProperties());
    }

    @Bean
    public KafkaMessageConverter<String, byte[]> b2gMessageConverter(@Qualifier("eventSerializer") Serializer eventSerializer) {
        return DefaultKafkaMessageConverter.builder().serializer(eventSerializer).build();
    }

    @Bean(destroyMethod = "shutdown")
    public Fetcher b2gFetcher(ConsumerFactory<String, byte[]> kafkaConsumerFactory, KafkaMessageConverter<String, byte[]> kafkaMessageConverter) {
        return AsyncFetcher.<String, byte[]>builder().consumerFactory(kafkaConsumerFactory)
                .bufferFactory(() -> new SortedKafkaMessageBuffer(this.properties.getFetcher().getBufferSize()))
                .messageConverter(kafkaMessageConverter)
                .topic(this.properties.getDefaultTopic())
                .pollTimeout(this.properties.getFetcher().getPollTimeout(), TimeUnit.MILLISECONDS).build();
    }


    @Bean
    public KafkaMessageSource b2gMessageSource(Fetcher kafkaFetcher) {
        return new KafkaMessageSource(kafkaFetcher);
    }
} 
```

And the following EventProcessor:

```
package b2ggateway.out.transit;

import org.axonframework.config.ProcessingGroup;
import org.axonframework.eventhandling.EventHandler;
import org.axonframework.messaging.Message;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import api.events.IESent;


@Transactional
@ProcessingGroup("kafka-event-processor")
@Service
public class EventHandler {

    //Must do that because it seems axon still deliver the message to this method
    @SuppressWarnings("ConstantConditions")
    @EventHandler
    public void handle(Message<IESent> ieSentMessage) {
        // Must check the type because axon is delivering all events to this method event not of type IESent
        if (ieSentMessage.getPayload() instanceof IESent) {
             System.out.println(ieSentMessage.getPayload())
        }
    }
}
```

I have observed that the KafkaTrackingTocken was not assigned to all partitions of my topic, I don't understand why. What should it to make it work? I tried to manually delete the token and it seems even worse because know the token does not contain any token/tokenType in database in table TokenEntry. It just an empty segment.
