### ISSUE TITLE
Tracking Token Updated if Creating a Publisher Fails

### ISSUE THREAD

**Issue by n3ziniuka5** [AxonFramework/extension-kafka#454]
### Basic information

I am setting up Axon to publish events to Kafka. I've tried various confirmation and event processor modes, and in all combinations I've managed to reproduce an issue when the tracking token is updated when Kafka is down, losing some events when Kafka is back up.

I am not fully up to speed with Axon internals, but one thing that jumps out in `KafkaPublisher.send` is that only Kafka commit happens under `uow.onPrepareCommit`. Other important steps, such as creation of the producer and sending of the message, both of which can throw exceptions, happen outside of it.

* Axon Framework version: 4.8.2
* JDK version:  17
* Kafka Extension version: 4.8.0

### Steps to reproduce

I used the following spring boot configuration to publish events to Kafka:
```yaml
axon:
  kafka:
    bootstrap-servers: localhost:9092
    client-id: axon-kafka-test
    default-topic: local.event
    properties:
      security.protocol: PLAINTEXT

    publisher:
      confirmation-mode: transactional

    producer:
      transaction-id-prefix: axon-kafka-test
      event-processor-mode: pooled-streaming
```

Steps to reproduce:
- Start Axon application
- Invoke a command that produces some events
- Confirm received events in Kafka, note the token sequence number in token store
- Shut down Kafka
- Invoke a command that produces some events
- Note how sequence number in token store has increased
- Stop Axon application
- Start Kafka
- Start Axon application
- Confirm missing event(s) in Kafka

### Expected behaviour

Kafka event processor's tracking token shouldn't be updated, and all events should eventually be published to Kafka when it recovers.

### Actual behaviour

Kafka event processor's tracking token  is updated even while Kafka is down.
